### ISSUE TITLE
[raphael] Popup Front Camera not extending when 48MPFix is active

### ISSUE THREAD

**Issue by c0deright** [XEonAX/ANXCamera#11]
## Summary

App works fine, no crashes, all good. When addon _48MPFix_ is enabled via Magisk, front camera won't extend anymore.

## Details

* **ANXCamera 139 active** via Magisk & **ANX48MPfix 129 disabled**
  * ANXCamera and other Cam apps can use front camera, front camera is driven up and down via motor
* **ANXCamera 139 active** via Magisk & **ANX48MPfix 129 active**
  * ANXCamera and other Cam apps can use front camera but front camera is staying in the device, not driven up via motor
  * Video images captured and displayed on the screen are black as expected when cam is still in the device

## ROM

My device is running Lineage 16.0 selfcompiled:

```
% getprop | grep raphael                                                                                                                                                                 
[ro.bootimage.build.fingerprint]: [Xiaomi/raphael/raphael:9/PKQ1.181121.001/V10.3.12.0.PFKCNXM:user/release-keys]
[ro.build.description]: [raphael-user 9 PKQ1.181121.001 V10.3.12.0.PFKCNXM release-keys]
[ro.build.display.id]: [lineage_raphael-userdebug 9 PQ3A.190801.002 eng.ubuntu.20190910.005629 test-keys]
[ro.build.fingerprint]: [Xiaomi/raphael/raphael:9/PKQ1.181121.001/V10.3.12.0.PFKCNXM:user/release-keys]
[ro.build.flavor]: [lineage_raphael-userdebug]
[ro.build.product]: [raphael]
[ro.lineage.device]: [raphael]
[ro.lineage.display.version]: [16.0-20190910-UNOFFICIAL-raphael]
[ro.lineage.version]: [16.0-20190910-UNOFFICIAL-raphael]
[ro.modversion]: [16.0-20190910-UNOFFICIAL-raphael]
[ro.product.board]: [raphael]
[ro.product.device]: [raphael]
[ro.product.name]: [raphael]
[ro.product.vendor.device]: [raphael]
[ro.product.vendor.name]: [raphael]
[ro.vendor.build.fingerprint]: [Xiaomi/raphael_eea/raphael:9/PKQ1.181121.001/V10.3.1.0.PFKEUXM:user/release-keys]
```

My ROM is based on repositories mentioned in https://forum.xda-developers.com/k20-pro/development/rom-lineage-15-1-t3949282:

* https://github.com/TingyiChen/device_xiaomi_raphael
* https://github.com/TingyiChen/kernel_xiaomi_sm8150
* https://github.com/TingyiChen/vendor_xiaomi_raphael

```
% cat .repo/local_manifests/roomservice.xml
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="TingyiChen/device_xiaomi_raphael" path="device/xiaomi/raphael" remote="github" />
  <project name="TingyiChen/kernel_xiaomi_sm8150" path="kernel/xiaomi/sm8150" remote="github" />
  <project name="TingyiChen/vendor_xiaomi_raphael" path="vendor/xiaomi/raphael" remote="github" />
  <project name="LineageOS/android_packages_resources_devicesettings" path="packages/resources/devicesettings" remote="github" revision="lineage-16.0" />
</manifest>
```

[logcat.txt](https://github.com/XEonAX/ANXCamera/files/3594922/logcat.txt) (at 11:33:25 I press the touch button to switch from camera 2 (back) to camera 1 (popup front camera)

**Comment by XEonAX** [comment]
@nckmml Any idea?

**Comment by nckmml** [comment]
old issue. Should be fixed by now with the background service that is present in lineage for raphael and davinci and is only to be found in roms built with old trees. Rom devs have to fix in their trees. Can be closed.

**Comment by XEonAX** [comment]
Closing this assuming fixed by rom devs.
