### ISSUE TITLE
Lavender 48mp not working on Android 10

### ISSUE THREAD

**Issue by DjordjeMancic97** [XEonAX/ANXCamera#17]
48mp mode takes pictures but they come out as 2mp

**Comment by theghost9** [comment]
> وضع 48mp يلتقط الصور ولكنه يخرج كـ 2mp

**Comment by XEonAX** [comment]
Have you flashed the 48mpfix?

**Comment by DjordjeMancic97** [comment]
Tried different versions in combination with fixes nothing worked. At the end I switched from Pixel Experience to other rom and it worked. Issue seems to be only on PE rom. Probably not issue on your end.
