### ISSUE TITLE
[AppCrash] v169 violet Camera app disabled

### ISSUE THREAD

**Issue by Ashesh3** [XEonAX/ANXCamera#20]
**Describe the bug**
Flashing vendor libs makes the device not boot anymore, Also without vendor the app is renamed to "Camera has been disabled" and constantly crashes

**To Reproduce**
1. Uninstall any previous versions of ANX Camera
2. Reboot to recovery
3. Flash `ANXCameraUnity_169.HonestAfraidGuineafowl.zip`
4. Reboot
5. Camera app has been renamed to "Camera has been disabled"
6. Reboot to recovery and flash `ANXVendorLibs_169.HonestAfraidGuineafowl.zip`
7. Device doesn't boot till i remove that module from magisk (using recovery)

**Expected behavior**
Camera app should work, flashing vendor libs shouldn't make the device not bootable

**Screenshots**
![image](https://user-images.githubusercontent.com/3626859/75083715-f979d300-5540-11ea-93c6-1ea806b6dac3.png)

**Phone (please complete the following information):**
 - Device: Redmi Note 7 Pro
 - CodeName: violet
 - ROM: Pixel Experience 9 PLUS
 - Vendor Version 
 - Custom Vendor No
 - Official Miui Pie ROM available for your device? Yes

**Additional context**
None

**Attach LogCat after doing the following**
Boot Logs (with vendor) : https://del.dog/yweestiwac.log
Camera crash logs (without vendor): https://del.dog/unebesodic

**Telegram username**
@DedSec1337

**Additional context**
I see many people are reporting the same issue in group chat.

**Comment by XEonAX** [comment]
V169 didn't support P,
V174 supports P, try this.

**Comment by Ashesh3** [comment]
V174 works great on my Pie, confirmed.
