### ISSUE TITLE
Wich Version for LineageOS 16 (Android 9) Poco F1

### ISSUE THREAD

**Issue by lunainvictum** [XEonAX/ANXCamera#30]
Hello! 

I installed the latest Anxcamera ANXCameraUnity_185.SaltyIntelligentPlainsqueaker.zip and as Addon ANXVendorLibs_182.AcidicVirtualAnhinga.zip because Addon vor 185 dont exist.

But the App crash immediately. So i tried V182 and Addon V182. But this crash too.

Then i searched im internet, and found out that it could be that V185/182 is only for Android 10. 

But im using Android 9. And dont know wich Version could i use.

**Comment by XEonAX** [comment]
v180 is last pie version
