### ISSUE TITLE
Add device: Poco X3 NFC

### ISSUE THREAD

**Issue by gsantner** [XEonAX/ANXCamera#35]
Hi tried to install the latest release on Poco X3 device (`ANXFrameworkUnity_190.BountifulDistantHapuka.zip`).  
However device not boots after installing, also not when additionally installing the "bootloop fix" package.

The device is not listed in the list of supported devices, so wanted to ask if it's possible to support this device too.

**Comment by XEonAX** [comment]
It might be supported in future builds

**Comment by RomanTheLegend** [comment]
Use v185 - as far as I understand, it's for devices/ROMs with stock vendor. Functionality is limited to basic though.
