### ISSUE TITLE
Camera error - Can't connect 

### ISSUE THREAD

**Issue by hsantanna** [XEonAX/ANXCamera#4]
When I open ANX Camera, I get an error saying that can't connect to the camera.

I'm on cepheus (mi9 global), with pixel experience rom.

Tried to update vendor flashing the latest version avaliable here: https://xiaomifirmwareupdater.com/
Stable or Development vendor, with no effect.

Gcam will not work either.

**Comment by XEonAX** [comment]
what version anxcamera? what's your ro.product.device?

**Comment by hsantanna** [comment]
anxcamera 129 
I figured out that it really was a vendor firmware issue and It was really hard to me to solve that, but now It works.
Thank you for the atention and for this good software.
Please keep going with this great work.
