### ISSUE TITLE
Portrait mode crashes camera on K20 Pro

### ISSUE THREAD

**Issue by ixanza** [XEonAX/ANXCamera#6]
Just flashed v137 on Raphael running AOSIP. When I select portrait mode the camera app crashes and continues to crash until camera data is cleared. 

Any specific logs would you need?

Here's a logcat of the camera app crashing
https://pastebin.com/dVdLrW75

**Comment by XEonAX** [comment]
Hi, I checked the logs, But according to this Camera service has already crashed.

Can you do the following:
1. Restart phone
2. Wait for it to idle
3. Clear Logs
4. Start Camera
5. Take a photo normally
6. Switch to portrait mode
7. Hopefully it will crash
8. Get the Logcat

**Comment by ixanza** [comment]
Sorry for the long wait. I was unable to copy the log to clipboard so I uploaded the text file

https://drive.google.com/file/d/1-ILY4cdANsS_vDm9GI-PmXHndwxhPgD_/view?usp=drivesdk

**Comment by RealAkito** [comment]
Same problem for davinci, davinciin (Mi 9T/Redmi K20)

**Comment by nujabse** [comment]
Same problem on mi 9

**Comment by mi-girl** [comment]
For my Mi 9 this problem was fixed in v158. But in v164 it came back.
Steps to reproduce:
1. Open anxcamera
2. Switch to portrait mode
3. Switch to any other mode e.g. foto
5. anxcamera freezes and after some delay it crashes 
6. After that anxcamera cannot be started anymore. A reboot is required.

**Comment by XEonAX** [comment]
Portrait Mode requires latest q48mpfix, cam hal denial fixes in rom or selinux permissive

Portrait mode should work after this.
