### ISSUE TITLE
Orientation Bug

### ISSUE THREAD

**Issue by SaktisImpreza** [XEonAX/ANXCamera#7]
When taking pictures in portrait (not mistaken with portrait mode), and sending the picture 
to (Telegram, Discord), the picture will be changed to 90 degrees anticlockwise.

Whyred*

**Comment by XEonAX** [comment]
AEonAX, [20.03.20 20:09]
is this fixed?

Saktis Impreza, [20.03.20 20:09]
[In reply to AEonAX]
yes....*blames Enforcing SELinux on Pie*
